// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kebtjycjbafigfecvlvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlYnRqeWNqYmFmaWdmZWN2bHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDU3MDUsImV4cCI6MjA2OTg4MTcwNX0.Neq67MmGTjEfb4nnzs-uS45Zd3vIRmVOIRlIpQK4Cec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});